spring:
    aop:
        auto: true
        proxy-target-class: true
    datasource:
       url : jdbc:h2:mem:example-oauth2
       username : sa
       password :
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name : org.h2.Driver
    cache:
       type: simple
hsweb:
    app:
      name: hsweb-oauth2示例
      version: 3.0.0
    users:
      admin:
        name: 超级管理员
        username: admin
        password: admin
        roles: #用户的角色
        - id: admin
          name: 管理员
        - id: user
          name: 用户
        permissions:  # 用户的权限
        - id: test #权限标识,可以理解为资源
          actions: query,get,update,delete,add #用户持有对该资源的操作
          dataAccesses:   # 数据权限配置,此配置表示在对test进行query操作的时候,不能查询password和salt字段
          - action: query
            type: DENY_FIELDS
            fields:
            - comment
            - status